'use client';

import { useState, useCallback } from 'react';
import Config from "@/lib/config";

import "@/style/home.css";
import "@/style/tools.css";

const TOOL_URL  = `${Config.MAIN_DOMAIN_NO}/tools/generator/name/business-name-generator`;
const TOOL_NAME = "Business Name Generator";

const INDUSTRIES = [
  { label: "Select industry…", value: "" },
  { label: "Technology",       value: "technology & software" },
  { label: "E-commerce",       value: "e-commerce & retail" },
  { label: "Food & Beverage",  value: "food & beverage" },
  { label: "Health & Wellness",value: "health & wellness" },
  { label: "Finance",          value: "finance & fintech" },
  { label: "Education",        value: "education & e-learning" },
  { label: "Marketing",        value: "marketing & creative agency" },
  { label: "Real Estate",      value: "real estate" },
  { label: "Travel",           value: "travel & hospitality" },
  { label: "Fashion",          value: "fashion & apparel" },
  { label: "Fitness",          value: "fitness & sports" },
  { label: "Legal",            value: "legal & consulting" },
  { label: "Other",            value: "general business" },
];

const STYLES = [
  { label: "Any style",    value: "any" },
  { label: "Professional", value: "professional and trustworthy" },
  { label: "Creative",     value: "creative and playful" },
  { label: "Minimalist",   value: "minimal, one or two syllables" },
  { label: "Bold",         value: "bold and powerful" },
  { label: "Modern",       value: "modern tech startup style" },
];

const FAQ = [
  { q: "How are business names generated?",      a: "Names are generated by DeepSeek AI — a large language model that creates unique, memorable names based on your industry, keywords, and style preference. Every batch is different." },
  { q: "Are the generated names trademarked?",   a: "No. The tool generates name ideas for inspiration only. Always search trademark databases and check domain availability before using any name commercially." },
  { q: "Can I check domain availability?",       a: "We show the name and tagline only. We recommend checking namecheap.com or instantdomainsearch.com after getting your results." },
  { q: "How many names do I get per generation?", a: "You get 6 unique business names per click, each with a tagline and short explanation of why the name works." },
  { q: "Is any of my input stored?",             a: "Your keywords and industry selection are sent to the DeepSeek API to generate names and are not stored by us. See the DeepSeek privacy policy for their data practices." },
];

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: Config.SITE_NAME,
  url: Config.MAIN_DOMAIN_NO,
  potentialAction: {
    "@type": "SearchAction",
    target: `${Config.MAIN_DOMAIN_NO}/search?q={search_term_string}`,
    "query-input": "required name=search_term_string",
  },
};

const softwareAppJsonLd = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: TOOL_NAME,
  url: TOOL_URL,
  applicationCategory: "BusinessApplication",
  description: "Free AI business name generator powered by DeepSeek. Get 6 unique business name ideas with taglines based on your industry and keywords. No signup required.",
  operatingSystem: "Any — Web Browser",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
    availability: "https://schema.org/InStock",
  },
  author: { "@type": "Organization", name: Config.SITE_NAME, url: Config.MAIN_DOMAIN_NO },
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: FAQ.map((f) => ({
    "@type": "Question",
    name: f.q,
    acceptedAnswer: { "@type": "Answer", text: f.a },
  })),
};

const breadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home",  item: Config.MAIN_DOMAIN_NO },
    { "@type": "ListItem", position: 2, name: "Tools", item: `${Config.MAIN_DOMAIN_NO}/tools` },
    { "@type": "ListItem", position: 3, name: TOOL_NAME, item: TOOL_URL },
  ],
};

interface BusinessName {
  name:    string;
  tagline: string;
  reason:  string;
}

// ── Tool section ──────────────────────────────────────────────────────────────
function BusinessNameSection() {
  const [industry, setIndustry]   = useState("");
  const [keywords, setKeywords]   = useState("");
  const [style, setStyle]         = useState("any");
  const [names, setNames]         = useState<BusinessName[]>([]);
  const [loading, setLoading]     = useState(false);
  const [errMsg, setErrMsg]       = useState<string | null>(null);
  const [copied, setCopied]       = useState<string | null>(null);
  const [count, setCount]         = useState(0);

  const handleGenerate = useCallback(async () => {
    if (!industry && !keywords.trim()) {
      setErrMsg("Please enter an industry or at least one keyword.");
      return;
    }

    setLoading(true);
    setErrMsg(null);
    setCopied(null);
    setNames([]);

    try {
      const res = await fetch("/api/generate-business-names", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ industry, keywords, style }),
      });

      const data = await res.json() as { names?: BusinessName[]; error?: string };

      if (!res.ok || data.error) {
        throw new Error(data.error ?? `Server error ${res.status}`);
      }

      if (!Array.isArray(data.names) || data.names.length === 0) {
        throw new Error("No names returned. Please try again.");
      }

      setNames(data.names);
      setCount((c) => c + 1);
    } catch (err) {
      setErrMsg(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setLoading(false);
    }
  }, [industry, keywords, style]);

  const copyName = (name: string) => {
    navigator.clipboard.writeText(name).then(() => {
      setCopied(name);
      setTimeout(() => setCopied(null), 2000);
    });
  };

  return (
    <section id="generator" className="converter-preview" aria-labelledby="generator-h2">
      <div className="converter-container">
        <h2 id="generator-h2" className="converter-h2">{TOOL_NAME}</h2>

        <div className="converter-box">
          {/* ── Inputs ── */}
          <div className="converter-input-wrapper">
            <div className="rng-row" style={{ marginBottom: 16 }}>
              <div className="rng-field" style={{ flex: 1 }}>
                <label htmlFor="industry-select" className="converter-label">Industry</label>
                <select
                  id="industry-select"
                  className="rng-input"
                  value={industry}
                  onChange={(e) => setIndustry(e.target.value)}
                  aria-label="Business industry"
                >
                  {INDUSTRIES.map((i) => (
                    <option key={i.value} value={i.value}>{i.label}</option>
                  ))}
                </select>
              </div>

              <div className="rng-field" style={{ flex: 1 }}>
                <label htmlFor="style-select" className="converter-label">Style</label>
                <select
                  id="style-select"
                  className="rng-input"
                  value={style}
                  onChange={(e) => setStyle(e.target.value)}
                  aria-label="Name style preference"
                >
                  {STYLES.map((s) => (
                    <option key={s.value} value={s.value}>{s.label}</option>
                  ))}
                </select>
              </div>
            </div>

            <label htmlFor="keywords-input" className="converter-label">
              Keywords or description
            </label>
            <div className="converter-input-controls">
              <textarea
                id="keywords-input"
                className="converter-input"
                style={{ minHeight: 80, resize: "vertical" }}
                placeholder="e.g. fast delivery, eco-friendly packaging, local artisan food…"
                value={keywords}
                onChange={(e) => setKeywords(e.target.value)}
                aria-label="Business keywords or description"
              />
              {keywords && (
                <button
                  className="converter-clear-btn"
                  onClick={() => setKeywords("")}
                  aria-label="Clear keywords"
                  title="Clear"
                >
                  ✕
                </button>
              )}
            </div>
            <span className="converter-help-text">
              Describe your business idea — the more detail, the better the names
            </span>
          </div>

          {/* ── Generate button ── */}
          <div className="rng-controls" style={{ marginTop: 0 }}>
            <button
              className={`rng-generate-btn${loading ? " rolling" : ""}`}
              onClick={handleGenerate}
              disabled={loading}
              aria-label="Generate business names"
            >
              {loading ? "⟳ Generating with AI…" : count === 0 ? "✦ Generate Business Names" : "✦ Generate More Names"}
            </button>
          </div>

          {/* ── Error ── */}
          {errMsg && (
            <div className="converter-empty-state" role="alert" aria-live="assertive">
              <p>⚠ {errMsg}</p>
            </div>
          )}

          {/* ── Results ── */}
          {names.length > 0 && !errMsg && (
            <>
              <div
                className="converter-outputs converter-outputs-grid"
                role="region"
                aria-live="polite"
                aria-label="Generated business names"
              >
                {names.map((item) => (
                  <div
                    key={item.name}
                    className={`converter-output${copied === item.name ? " copied" : ""}`}
                    onClick={() => copyName(item.name)}
                    role="button"
                    tabIndex={0}
                    onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") copyName(item.name); }}
                    aria-label={`Copy business name: ${item.name}`}
                    title="Click to copy name"
                  >
                    <span className="output-label">Business Name</span>
                    <code className="output-code" style={{ fontSize: "clamp(16px, 2.5vw, 24px)", wordBreak: "break-word" }}>
                      {item.name}
                    </code>
                    <span style={{ fontSize: 12, color: "var(--accent)", fontFamily: "var(--mono)", fontStyle: "italic", marginBottom: 8, display: "block" }}>
                      &ldquo;{item.tagline}&rdquo;
                    </span>
                    <span className="output-desc">{item.reason}</span>
                    {copied === item.name && <span className="output-feedback">✓ Copied!</span>}
                  </div>
                ))}
              </div>
              <p style={{ marginTop: 12, fontSize: 12, color: "var(--ink-3)", fontFamily: "var(--mono)" }}>
                Powered by DeepSeek AI · batch #{count} · click any card to copy
              </p>
            </>
          )}

          {/* ── Empty state ── */}
          {names.length === 0 && !errMsg && (
            <div className="converter-empty-state">
              <p>Fill in your industry and keywords, then click <strong>Generate Business Names</strong></p>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}

// ── Page ──────────────────────────────────────────────────────────────────────
export default function BusinessNameGeneratorPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareAppJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} />

      {/* HERO */}
      <section className="hero" aria-labelledby="hero-h1">
        <div className="hero-meta">
          <span className="dot dot-live" /> AI-Powered · DeepSeek · No Signup
        </div>
        <h1 id="hero-h1" className="hero-h1">
          Business Name Generator
          <br />
          <em>powered by AI.</em>
        </h1>
        <p className="hero-sub">
          Enter your industry and a few keywords — get 6 unique, AI-generated business name ideas
          with taglines instantly. Powered by DeepSeek AI. No signup, no ads, completely free.
        </p>
        <div className="hero-cta">
          <a href="#generator" className="btn btn-primary">Generate Names →</a>
          <a href="#how-it-works" className="btn btn-ghost">How it works</a>
        </div>
        <ul className="hero-stats" aria-label="Tool highlights">
          <li><strong>6</strong><span>names per batch</span></li>
          <li><strong>AI</strong><span>powered</span></li>
          <li><strong>13</strong><span>industries</span></li>
          <li><strong>Free</strong><span>forever</span></li>
        </ul>
      </section>

      {/* TOOL */}
      <BusinessNameSection />

      {/* HOW IT WORKS */}
      <section id="how-it-works" className="why" aria-labelledby="why-h2">
        <span className="eyebrow">/ 01 — How It Works</span>
        <h2 id="why-h2" className="section-h2">Describe your business. Get names.</h2>
        <div className="why-grid">
          <article className="why-card">
            <span className="why-num">01</span>
            <h3>Pick Your Industry</h3>
            <p>Choose from 13 categories — technology, food, finance, health, education, real estate, and more. This shapes the vocabulary the AI uses.</p>
          </article>
          <article className="why-card">
            <span className="why-num">02</span>
            <h3>Add Keywords</h3>
            <p>Describe your business in a few words. What do you do? Who do you serve? What makes you different? More detail means better names.</p>
          </article>
          <article className="why-card">
            <span className="why-num">03</span>
            <h3>AI Generates Names</h3>
            <p>DeepSeek AI generates 6 unique names — descriptive, abstract, metaphorical, and portmanteau styles — each with a tagline and explanation.</p>
          </article>
          <article className="why-card">
            <span className="why-num">04</span>
            <h3>Copy & Iterate</h3>
            <p>Click any name card to copy it. Not quite right? Refine your keywords and generate again. Each batch is fresh and different.</p>
          </article>
        </div>
      </section>

      {/* TIPS GUIDE */}
      <section className="why" aria-labelledby="tips-h2">
        <span className="eyebrow">/ 02 — Tips</span>
        <h2 id="tips-h2" className="section-h2">How to get better business names.</h2>
        <div className="formats-container">
          <div className="format-group">
            <h3 className="format-group-title">Write better keywords</h3>
            <div className="format-items">
              <div className="format-item">
                <strong>Be specific</strong>
                <p>Instead of "food delivery", try "healthy meal prep delivery for busy professionals in urban areas". Specificity produces more targeted names.</p>
                <code>Bad: "food" · Good: "organic meal kits for families"</code>
              </div>
              <div className="format-item">
                <strong>Include your values</strong>
                <p>Add adjectives that reflect your brand personality — sustainable, bold, calm, playful, premium, community-driven.</p>
                <code>Example: "sustainable, premium, minimalist coffee brand"</code>
              </div>
              <div className="format-item">
                <strong>Name your target audience</strong>
                <p>Who is your customer? Naming them in the prompt helps the AI generate names that resonate with that demographic.</p>
                <code>Example: "fitness app for women over 40"</code>
              </div>
            </div>
          </div>

          <div className="format-group">
            <h3 className="format-group-title">After you get names</h3>
            <div className="format-items">
              <div className="format-item">
                <strong>Check domain availability</strong>
                <p>A great business name needs a matching domain. Check availability on Namecheap, GoDaddy, or instantdomainsearch.com before committing.</p>
                <code>Tip: .com is best · .io works for tech · .co for startups</code>
              </div>
              <div className="format-item">
                <strong>Search trademarks</strong>
                <p>Before using any name, search USPTO (US), EUIPO (EU), or your national trademark database to ensure the name is not already registered.</p>
                <code>US: USPTO.gov · EU: EUIPO.europa.eu</code>
              </div>
              <div className="format-item">
                <strong>Test it with people</strong>
                <p>Say the name out loud. Ask 5 people what they think the business does. A good name communicates without explanation.</p>
                <code>Tip: if people mispronounce it, consider alternatives</code>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="faq" aria-labelledby="faq-h2">
        <span className="eyebrow">/ 03 — FAQ</span>
        <h2 id="faq-h2" className="section-h2">Questions people ask</h2>
        <div className="faq-list">
          {FAQ.map((f, i) => (
            <details key={i} className="faq-item">
              <summary>
                <span className="faq-q">{f.q}</span>
                <span className="faq-toggle" aria-hidden="true">+</span>
              </summary>
              <p>{f.a}</p>
            </details>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="cta">
        <h2>Ready to name your business?</h2>
        <a href="#generator" className="btn btn-primary btn-lg">Generate Names Now →</a>
      </section>
    </>
  );
}