export const dynamic = "force-static";

import type { Metadata } from "next";
import BusinessNameGenerator from "./BusinessNameGenerator";
import Config from "@/lib/config";

export const metadata: Metadata = {
  title: `Business Name Generator — AI-Powered Name Ideas for Any Industry | Free`,
  description: `Free AI Business Name Generator: get 6 unique business name ideas with taglines instantly. Powered by DeepSeek AI. Enter your industry and keywords — perfect names for startups, shops, and agencies. No signup, 100% free.`,
  keywords: [
    "business name generator",
    "AI business name generator",
    "company name generator",
    "startup name generator",
    "brand name generator",
    "business name ideas",
    "company name ideas",
    "creative business names",
    "free business name generator",
    "online business name generator",
    "small business name ideas",
    "shop name generator",
    "agency name generator",
    "tech company name generator",
    "restaurant name generator",
    "ecommerce business name",
    "name your business",
    "DeepSeek AI business names",
  ],
  authors: [{ name: `${Config.NAME_MAKE}` }],
  robots: { index: true, follow: true },
  alternates: { canonical: `${Config.MAIN_DOMAIN_NO}/tools/generator/name/business-name-generator` },
  openGraph: {
    title: `Business Name Generator — AI-Powered, Free & Instant`,
    description: `Get 6 unique AI-generated business names with taglines. Enter your industry and keywords — DeepSeek AI does the rest. Free, no signup required.`,
    url: `${Config.MAIN_DOMAIN_NO}/tools/generator/name/business-name-generator`,
    type: "website",
    siteName: Config.SITE_NAME,
    images: [
      {
        url: `${Config.MAIN_DOMAIN_NO}/icon.png`,
        width: 1200,
        height: 630,
        alt: `Business Name Generator — AI-Powered`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: `Business Name Generator — AI-Powered & Free`,
    description: `6 unique business names with taglines, generated by DeepSeek AI. Just enter your industry and keywords. Free, no signup.`,
  },
};

export default function BusinessNameGeneratorPage() {
  return <BusinessNameGenerator />;
}