'use client';

import { useState, useCallback } from 'react';
import Config from "@/lib/config";

import "@/style/home.css";
import "@/style/tools.css";

const TOOL_URL  = `${Config.MAIN_DOMAIN_NO}/tools/generator/name/cool-usernames-for-gamers`;
const TOOL_NAME = "Cool Usernames for Gamers";

const THEMES = [
  { label: "Any theme",        value: "" },
  { label: "FPS & Shooters",   value: "FPS shooters, military, tactical" },
  { label: "RPG & Fantasy",    value: "RPG fantasy, swords, magic, dragons" },
  { label: "Battle Royale",    value: "battle royale, survival, last man standing" },
  { label: "MOBA & Strategy",  value: "MOBA strategy, heroes, champions" },
  { label: "Horror & Dark",    value: "horror, dark, sinister, shadow" },
  { label: "Sci-Fi & Cyber",   value: "sci-fi, cyberpunk, futuristic, neon" },
  { label: "Mythical & Gods",  value: "mythology, gods, ancient warriors, legends" },
  { label: "Nature & Animals", value: "nature, animals, wolves, eagles, predators" },
  { label: "Funny & Meme",     value: "funny, ironic, meme culture, chaotic" },
  { label: "Minimalist",       value: "minimalist, short, clean, one word" },
];

const VIBES = [
  { label: "Any vibe",           value: "any" },
  { label: "Fierce & Dominant",  value: "fierce, dominant, intimidating" },
  { label: "Mysterious & Dark",  value: "mysterious, dark, shadowy" },
  { label: "Legendary & Epic",   value: "legendary, epic, mythic" },
  { label: "Funny & Chaotic",    value: "funny, chaotic, meme-worthy" },
  { label: "Clean & Minimal",    value: "clean, minimal, one or two syllables" },
  { label: "Aggressive & Bold",  value: "aggressive, bold, powerful" },
  { label: "Cosmic & Ethereal",  value: "cosmic, ethereal, celestial" },
];

const PLATFORMS = [
  { label: "Any platform",   value: "any" },
  { label: "Steam",          value: "Steam" },
  { label: "Xbox Live",      value: "Xbox Live" },
  { label: "PlayStation",    value: "PlayStation Network" },
  { label: "Battle.net",     value: "Battle.net" },
  { label: "Discord",        value: "Discord" },
  { label: "Twitch",         value: "Twitch" },
  { label: "Riot Games",     value: "Riot Games (League, Valorant)" },
];

const FAQ = [
  { q: "How are gamer usernames generated?",       a: "Usernames are generated by DeepSeek AI based on your chosen theme, vibe, platform, and optional keyword. The AI avoids generic names and creates unique, authentic handles every time." },
  { q: "Are the usernames guaranteed to be available?", a: "No. Username availability depends on the platform. Always check your chosen platform before trying to register. We recommend having a few backups ready." },
  { q: "Can I add numbers or underscores?",         a: "Yes. The AI naturally uses numbers, underscores, and camelCase when it fits the style. You can also add these manually after copying a name you like." },
  { q: "What platforms are these usernames good for?", a: "They work for any gaming platform — Steam, Xbox, PlayStation, Riot Games (League of Legends, Valorant), Battle.net, Discord, Twitch, and more." },
  { q: "Why does the AI avoid 'XxX_shadow_XxX' style names?", a: "That style became a meme. The AI is instructed to generate modern, authentic names that actually feel cool in today's gaming culture — not early 2010s MLG aesthetics." },
];

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: Config.SITE_NAME,
  url: Config.MAIN_DOMAIN_NO,
  potentialAction: {
    "@type": "SearchAction",
    target: `${Config.MAIN_DOMAIN_NO}/search?q={search_term_string}`,
    "query-input": "required name=search_term_string",
  },
};

const softwareAppJsonLd = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: TOOL_NAME,
  url: TOOL_URL,
  applicationCategory: "GameApplication",
  description: "Free AI-powered cool gaming username generator. Get 8 unique gamer tags by theme, vibe, and platform. Powered by DeepSeek. No signup required.",
  operatingSystem: "Any — Web Browser",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
    availability: "https://schema.org/InStock",
  },
  author: { "@type": "Organization", name: Config.SITE_NAME, url: Config.MAIN_DOMAIN_NO },
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: FAQ.map((f) => ({
    "@type": "Question",
    name: f.q,
    acceptedAnswer: { "@type": "Answer", text: f.a },
  })),
};

const breadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home",  item: Config.MAIN_DOMAIN_NO },
    { "@type": "ListItem", position: 2, name: "Tools", item: `${Config.MAIN_DOMAIN_NO}/tools` },
    { "@type": "ListItem", position: 3, name: TOOL_NAME, item: TOOL_URL },
  ],
};

interface GamerUsername {
  username: string;
  style:    string;
  meaning:  string;
}

// ── Tool section ──────────────────────────────────────────────────────────────
function GamerUsernameSection() {
  const [theme,     setTheme]     = useState("");
  const [vibe,      setVibe]      = useState("any");
  const [keyword,   setKeyword]   = useState("");
  const [platform,  setPlatform]  = useState("any");
  const [usernames, setUsernames] = useState<GamerUsername[]>([]);
  const [loading,   setLoading]   = useState(false);
  const [errMsg,    setErrMsg]    = useState<string | null>(null);
  const [copied,    setCopied]    = useState<string | null>(null);
  const [count,     setCount]     = useState(0);

  const handleGenerate = useCallback(async () => {
    setLoading(true);
    setErrMsg(null);
    setCopied(null);
    setUsernames([]);

    try {
      const res = await fetch("/api/generate-gamer-usernames", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ theme, vibe, keyword, platform }),
      });

      const data = await res.json() as { usernames?: GamerUsername[]; error?: string };

      if (!res.ok || data.error) {
        throw new Error(data.error ?? `Server error ${res.status}`);
      }

      if (!Array.isArray(data.usernames) || data.usernames.length === 0) {
        throw new Error("No usernames returned. Please try again.");
      }

      setUsernames(data.usernames);
      setCount((c) => c + 1);
    } catch (err) {
      setErrMsg(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setLoading(false);
    }
  }, [theme, vibe, keyword, platform]);

  const copyUsername = (username: string) => {
    navigator.clipboard.writeText(username).then(() => {
      setCopied(username);
      setTimeout(() => setCopied(null), 2000);
    });
  };

  return (
    <section id="generator" className="converter-preview" aria-labelledby="generator-h2">
      <div className="converter-container">
        <h2 id="generator-h2" className="converter-h2">Gamer Username Generator</h2>

        <div className="converter-box">
          {/* ── Inputs ── */}
          <div className="converter-input-wrapper">

            {/* Row 1: Theme + Vibe */}
            <div className="rng-row" style={{ marginBottom: 16 }}>
              <div className="rng-field" style={{ flex: 1 }}>
                <label htmlFor="theme-select" className="converter-label">Game Theme</label>
                <select
                  id="theme-select"
                  className="rng-input"
                  value={theme}
                  onChange={(e) => setTheme(e.target.value)}
                  aria-label="Game theme"
                >
                  {THEMES.map((t) => (
                    <option key={t.value} value={t.value}>{t.label}</option>
                  ))}
                </select>
              </div>

              <div className="rng-field" style={{ flex: 1 }}>
                <label htmlFor="vibe-select" className="converter-label">Username Vibe</label>
                <select
                  id="vibe-select"
                  className="rng-input"
                  value={vibe}
                  onChange={(e) => setVibe(e.target.value)}
                  aria-label="Username vibe"
                >
                  {VIBES.map((v) => (
                    <option key={v.value} value={v.value}>{v.label}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Row 2: Platform + Keyword */}
            <div className="rng-row" style={{ marginBottom: 16 }}>
              <div className="rng-field" style={{ flex: 1 }}>
                <label htmlFor="platform-select" className="converter-label">Platform</label>
                <select
                  id="platform-select"
                  className="rng-input"
                  value={platform}
                  onChange={(e) => setPlatform(e.target.value)}
                  aria-label="Gaming platform"
                >
                  {PLATFORMS.map((p) => (
                    <option key={p.value} value={p.value}>{p.label}</option>
                  ))}
                </select>
              </div>

              <div className="rng-field" style={{ flex: 1 }}>
                <label htmlFor="keyword-input" className="converter-label">
                  Keyword <span style={{ color: "var(--ink-3)", fontWeight: 400 }}>(optional)</span>
                </label>
                <div style={{ position: "relative" }}>
                  <input
                    id="keyword-input"
                    type="text"
                    className="rng-input"
                    placeholder="e.g. wolf, frost, void…"
                    value={keyword}
                    onChange={(e) => setKeyword(e.target.value)}
                    maxLength={20}
                    aria-label="Optional keyword"
                  />
                  {keyword && (
                    <button
                      onClick={() => setKeyword("")}
                      style={{
                        position: "absolute", right: 10, top: "50%",
                        transform: "translateY(-50%)",
                        background: "none", border: "none",
                        color: "var(--ink-3)", cursor: "pointer", fontSize: 14,
                      }}
                      aria-label="Clear keyword"
                    >
                      ✕
                    </button>
                  )}
                </div>
              </div>
            </div>

            <span className="converter-help-text">
              Mix and match options — or leave everything on Any for a fully random batch
            </span>
          </div>

          {/* ── Generate button ── */}
          <div className="rng-controls" style={{ marginTop: 0 }}>
            <button
              className={`rng-generate-btn${loading ? " rolling" : ""}`}
              onClick={handleGenerate}
              disabled={loading}
              aria-label="Generate gamer usernames"
            >
              {loading ? "⟳ Creating usernames…" : count === 0 ? "⚡ Generate Usernames" : "⚡ Generate More"}
            </button>
          </div>

          {/* ── Error ── */}
          {errMsg && (
            <div className="converter-empty-state" role="alert" aria-live="assertive">
              <p>⚠ {errMsg}</p>
            </div>
          )}

          {/* ── Results grid ── */}
          {usernames.length > 0 && !errMsg && (
            <>
              <div
                className="converter-outputs converter-outputs-grid"
                role="region"
                aria-live="polite"
                aria-label="Generated gamer usernames"
              >
                {usernames.map((u) => (
                  <div
                    key={u.username}
                    className={`converter-output${copied === u.username ? " copied" : ""}`}
                    onClick={() => copyUsername(u.username)}
                    role="button"
                    tabIndex={0}
                    onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") copyUsername(u.username); }}
                    aria-label={`Copy username: ${u.username}`}
                    title="Click to copy"
                  >
                    <span className="output-label">{u.style}</span>
                    <code
                      className="output-code"
                      style={{
                        fontSize: "clamp(15px, 2.2vw, 22px)",
                        wordBreak: "break-all",
                        letterSpacing: "-0.01em",
                      }}
                    >
                      {u.username}
                    </code>
                    <span className="output-desc">{u.meaning}</span>
                    {copied === u.username && (
                      <span className="output-feedback">✓ Copied!</span>
                    )}
                  </div>
                ))}
              </div>

              <p style={{ marginTop: 12, fontSize: 12, color: "var(--ink-3)", fontFamily: "var(--mono)" }}>
                Powered by DeepSeek AI · batch #{count} · click any card to copy
              </p>
            </>
          )}

          {/* ── Empty state ── */}
          {usernames.length === 0 && !errMsg && (
            <div className="converter-empty-state">
              <p>Choose your theme and vibe, then click <strong>Generate Usernames</strong></p>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}

// ── Page ──────────────────────────────────────────────────────────────────────
export default function CoolGamerUsernamesPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareAppJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} />

      {/* HERO */}
      <section className="hero" aria-labelledby="hero-h1">
        <div className="hero-meta">
          <span className="dot dot-live" /> AI-Powered · 8 per batch · No Signup
        </div>
        <h1 id="hero-h1" className="hero-h1">
          Cool Usernames
          <br />
          <em>for gamers.</em>
        </h1>
        <p className="hero-sub">
          Generate unique, authentic gamer usernames by theme, vibe, and platform.
          Powered by DeepSeek AI — no generic names, no cringe XxX style.
          8 fresh options per click, free, no signup.
        </p>
        <div className="hero-cta">
          <a href="#generator" className="btn btn-primary">Generate Usernames →</a>
          <a href="#how-it-works" className="btn btn-ghost">How it works</a>
        </div>
        <ul className="hero-stats" aria-label="Tool highlights">
          <li><strong>8</strong><span>per batch</span></li>
          <li><strong>10</strong><span>game themes</span></li>
          <li><strong>7</strong><span>vibes</span></li>
          <li><strong>Free</strong><span>forever</span></li>
        </ul>
      </section>

      {/* TOOL */}
      <GamerUsernameSection />

      {/* HOW IT WORKS */}
      <section id="how-it-works" className="why" aria-labelledby="why-h2">
        <span className="eyebrow">/ 01 — How It Works</span>
        <h2 id="why-h2" className="section-h2">Pick a vibe. Get 8 usernames.</h2>
        <div className="why-grid">
          <article className="why-card">
            <span className="why-num">01</span>
            <h3>Choose Your Theme</h3>
            <p>FPS, RPG, Battle Royale, Sci-Fi, Horror, Mythology — or leave it on Any for a fully random mix across all gaming genres.</p>
          </article>
          <article className="why-card">
            <span className="why-num">02</span>
            <h3>Set the Vibe</h3>
            <p>Fierce, Mysterious, Legendary, Funny, Minimal, Cosmic — the vibe shapes the personality of every name in the batch.</p>
          </article>
          <article className="why-card">
            <span className="why-num">03</span>
            <h3>Add a Keyword</h3>
            <p>Optionally drop in a word you love — "wolf", "void", "frost" — and the AI weaves it into the generated names creatively.</p>
          </article>
          <article className="why-card">
            <span className="why-num">04</span>
            <h3>Copy in One Click</h3>
            <p>Click any username card to instantly copy it. Generate again for a fresh batch — each one is different thanks to high AI creativity settings.</p>
          </article>
        </div>
      </section>

      {/* USERNAME STYLES GUIDE */}
      <section className="why" aria-labelledby="styles-h2">
        <span className="eyebrow">/ 02 — Styles</span>
        <h2 id="styles-h2" className="section-h2">What makes a great gamer username?</h2>
        <div className="formats-container">
          <div className="format-group">
            <h3 className="format-group-title">The classics</h3>
            <div className="format-items">
              <div className="format-item">
                <strong>Fierce & Intimidating</strong>
                <p>Names that make opponents pause before the match starts. Short, aggressive, unmistakable. Think apex predator energy.</p>
                <code>Examples: VoidCleaver · ShadowFangs · IronJawline</code>
              </div>
              <div className="format-item">
                <strong>Legendary & Mythic</strong>
                <p>Names that feel like they belong in a Hall of Fame. References to gods, ancient warriors, and epic lore without being overdone.</p>
                <code>Examples: Acheron · WyrmSlayer · CelestialRuins</code>
              </div>
              <div className="format-item">
                <strong>Mysterious & Dark</strong>
                <p>Names with depth. A mysterious username makes people wonder who you are before they even see your stats.</p>
                <code>Examples: NullTrace · AbyssKeeper · EclipsedSoul</code>
              </div>
            </div>
          </div>

          <div className="format-group">
            <h3 className="format-group-title">Modern styles</h3>
            <div className="format-items">
              <div className="format-item">
                <strong>Minimalist</strong>
                <p>One or two syllables, clean and sharp. These names are impossible to forget and look great on leaderboards and stream overlays.</p>
                <code>Examples: Kael · Vex · Dusk · Nox</code>
              </div>
              <div className="format-item">
                <strong>Funny & Chaotic</strong>
                <p>Self-aware, ironic, or absurdist. Names that make teammates laugh and enemies underestimate you — until you top the scoreboard.</p>
                <code>Examples: YourAimIsBad · PleaseRefund · TouchGrass420</code>
              </div>
              <div className="format-item">
                <strong>Cosmic & Sci-Fi</strong>
                <p>Futuristic, ethereal, cyberpunk. Names that feel like they belong in a space opera or neon-drenched dystopia.</p>
                <code>Examples: NeoSingularity · QuantumBleed · PulsarWarden</code>
              </div>
            </div>
          </div>

          <div className="format-group">
            <h3 className="format-group-title">Platform tips</h3>
            <div className="format-items">
              <div className="format-item">
                <strong>Steam & PC</strong>
                <p>No character limit pressure — longer, more creative names work well. Spaces are allowed but underscores look cleaner on scoreboards.</p>
                <code>Max: 32 characters · Spaces allowed</code>
              </div>
              <div className="format-item">
                <strong>Xbox & PlayStation</strong>
                <p>Strict character limits (12-16 chars). Shorter, punchy names perform better. Avoid spaces — use camelCase or underscores.</p>
                <code>Xbox: 12 chars · PSN: 16 chars</code>
              </div>
              <div className="format-item">
                <strong>Riot Games (Valorant, LoL)</strong>
                <p>You get a name plus a tag (#1234). Keep the display name short and memorable — the tag is auto-assigned or custom.</p>
                <code>Display name: up to 16 chars · Tag: 3-5 chars</code>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="faq" aria-labelledby="faq-h2">
        <span className="eyebrow">/ 03 — FAQ</span>
        <h2 id="faq-h2" className="section-h2">Questions people ask</h2>
        <div className="faq-list">
          {FAQ.map((f, i) => (
            <details key={i} className="faq-item">
              <summary>
                <span className="faq-q">{f.q}</span>
                <span className="faq-toggle" aria-hidden="true">+</span>
              </summary>
              <p>{f.a}</p>
            </details>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="cta">
        <h2>Find your perfect gamer tag.</h2>
        <a href="#generator" className="btn btn-primary btn-lg">Generate Usernames Now →</a>
      </section>
    </>
  );
}