'use client';

import { useState, useCallback } from 'react';
import Config from "@/lib/config";

import "@/style/home.css";
import "@/style/tools.css";

const TOOL_URL  = `${Config.MAIN_DOMAIN_NO}/startup-idea-generator`;
const TOOL_NAME = "Startup Idea Generator";

const INDUSTRIES = [
  { label: "Any industry",       value: "" },
  { label: "AI & Machine Learning", value: "AI & machine learning" },
  { label: "SaaS & Developer Tools", value: "SaaS & developer tools" },
  { label: "Health & MedTech",   value: "health & medtech" },
  { label: "FinTech",            value: "fintech & financial services" },
  { label: "EdTech",             value: "education & edtech" },
  { label: "E-commerce & Retail", value: "e-commerce & retail" },
  { label: "CleanTech",          value: "cleantech & sustainability" },
  { label: "Food & AgriTech",    value: "food & agritech" },
  { label: "Real Estate & PropTech", value: "real estate & proptech" },
  { label: "Travel & Mobility",  value: "travel & mobility" },
  { label: "Creator Economy",    value: "creator economy & media" },
  { label: "HR & Future of Work", value: "HR & future of work" },
  { label: "Security & Privacy", value: "cybersecurity & privacy" },
];

const STAGES = [
  { label: "Any founder background", value: "any" },
  { label: "First-time founder",     value: "first-time founder, no tech background" },
  { label: "Technical founder",      value: "technical founder, engineering background" },
  { label: "Domain expert",          value: "domain expert in the chosen industry" },
  { label: "Solo indie hacker",      value: "solo indie hacker, low budget" },
  { label: "Well-funded team",       value: "well-funded team of 3-5 people" },
];

const DIFFICULTY_META: Record<string, { label: string; color: string }> = {
  easy:   { label: "Easy",   color: "var(--accent)" },
  medium: { label: "Medium", color: "#f5a623" },
  hard:   { label: "Hard",   color: "#e05252" },
};

const FAQ = [
  { q: "How are startup ideas generated?",        a: "Ideas are generated by DeepSeek AI, an advanced large language model. It analyses your industry, problem, and audience inputs to produce specific, actionable startup concepts — not generic vague suggestions." },
  { q: "Are these ideas validated?",              a: "No. The ideas are AI-generated starting points for your own research and validation. Always talk to potential customers, check market size, and validate demand before building." },
  { q: "What does the difficulty rating mean?",   a: "Easy = can be launched quickly with minimal capital, often a service or no-code tool. Medium = requires some development or industry knowledge. Hard = technically complex, capital-intensive, or heavily regulated." },
  { q: "Can I get more ideas on the same topic?", a: "Yes. Click Generate Again to get a fresh batch. The AI uses a high creativity setting so each batch is different. Refine your inputs for more targeted results." },
  { q: "Is my input stored or shared?",           a: "Your inputs are sent to the DeepSeek API to generate ideas and are not stored by us. Refer to the DeepSeek privacy policy for their data practices." },
];

const websiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: Config.SITE_NAME,
  url: Config.MAIN_DOMAIN_NO,
  potentialAction: {
    "@type": "SearchAction",
    target: `${Config.MAIN_DOMAIN_NO}/search?q={search_term_string}`,
    "query-input": "required name=search_term_string",
  },
};

const softwareAppJsonLd = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: TOOL_NAME,
  url: TOOL_URL,
  applicationCategory: "BusinessApplication",
  description: "Free AI startup idea generator powered by DeepSeek. Get 4 specific, actionable startup ideas with problem, solution, target audience, and revenue model. No signup required.",
  operatingSystem: "Any — Web Browser",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
    availability: "https://schema.org/InStock",
  },
  author: { "@type": "Organization", name: Config.SITE_NAME, url: Config.MAIN_DOMAIN_NO },
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: FAQ.map((f) => ({
    "@type": "Question",
    name: f.q,
    acceptedAnswer: { "@type": "Answer", text: f.a },
  })),
};

const breadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home",  item: Config.MAIN_DOMAIN_NO },
    { "@type": "ListItem", position: 2, name: "Tools", item: `${Config.MAIN_DOMAIN_NO}/tools` },
    { "@type": "ListItem", position: 3, name: TOOL_NAME, item: TOOL_URL },
  ],
};

interface StartupIdea {
  name:       string;
  tagline:    string;
  problem:    string;
  solution:   string;
  target:     string;
  revenue:    string;
  difficulty: string;
}

// ── Tool section ──────────────────────────────────────────────────────────────
function StartupIdeaSection() {
  const [industry,  setIndustry]  = useState("");
  const [problem,   setProblem]   = useState("");
  const [audience,  setAudience]  = useState("");
  const [stage,     setStage]     = useState("any");
  const [ideas,     setIdeas]     = useState<StartupIdea[]>([]);
  const [loading,   setLoading]   = useState(false);
  const [errMsg,    setErrMsg]    = useState<string | null>(null);
  const [copied,    setCopied]    = useState<string | null>(null);
  const [count,     setCount]     = useState(0);
  const [expanded,  setExpanded]  = useState<string | null>(null);

  const handleGenerate = useCallback(async () => {
    if (!industry && !problem.trim() && !audience.trim()) {
      setErrMsg("Please fill in at least one field — industry, problem, or audience.");
      return;
    }

    setLoading(true);
    setErrMsg(null);
    setCopied(null);
    setIdeas([]);
    setExpanded(null);

    try {
      const res = await fetch("/api/generate-startup-ideas", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ industry, problem, audience, stage }),
      });

      const data = await res.json() as { ideas?: StartupIdea[]; error?: string };

      if (!res.ok || data.error) {
        throw new Error(data.error ?? `Server error ${res.status}`);
      }

      if (!Array.isArray(data.ideas) || data.ideas.length === 0) {
        throw new Error("No ideas returned. Please try again.");
      }

      setIdeas(data.ideas);
      setCount((c) => c + 1);
    } catch (err) {
      setErrMsg(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setLoading(false);
    }
  }, [industry, problem, audience, stage]);

  const copyIdea = (idea: StartupIdea) => {
    const text = `${idea.name}\n"${idea.tagline}"\n\nProblem: ${idea.problem}\nSolution: ${idea.solution}\nTarget: ${idea.target}\nRevenue: ${idea.revenue}`;
    navigator.clipboard.writeText(text).then(() => {
      setCopied(idea.name);
      setTimeout(() => setCopied(null), 2000);
    });
  };

  const toggleExpanded = (name: string) => {
    setExpanded((prev) => (prev === name ? null : name));
  };

  return (
    <section id="generator" className="converter-preview" aria-labelledby="generator-h2">
      <div className="converter-container">
        <h2 id="generator-h2" className="converter-h2">{TOOL_NAME}</h2>

        <div className="converter-box">

          {/* ── Inputs ── */}
          <div className="converter-input-wrapper">

            {/* Row 1: Industry + Stage */}
            <div className="rng-row" style={{ marginBottom: 16 }}>
              <div className="rng-field" style={{ flex: 1 }}>
                <label htmlFor="industry-select" className="converter-label">Industry / Space</label>
                <select
                  id="industry-select"
                  className="rng-input"
                  value={industry}
                  onChange={(e) => setIndustry(e.target.value)}
                  aria-label="Industry"
                >
                  {INDUSTRIES.map((i) => (
                    <option key={i.value} value={i.value}>{i.label}</option>
                  ))}
                </select>
              </div>

              <div className="rng-field" style={{ flex: 1 }}>
                <label htmlFor="stage-select" className="converter-label">Founder background</label>
                <select
                  id="stage-select"
                  className="rng-input"
                  value={stage}
                  onChange={(e) => setStage(e.target.value)}
                  aria-label="Founder background"
                >
                  {STAGES.map((s) => (
                    <option key={s.value} value={s.value}>{s.label}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Problem textarea */}
            <label htmlFor="problem-input" className="converter-label">
              Problem or pain point <span style={{ color: "var(--ink-3)", fontWeight: 400 }}>(optional)</span>
            </label>
            <div className="converter-input-controls" style={{ marginBottom: 12 }}>
              <textarea
                id="problem-input"
                className="converter-input"
                style={{ minHeight: 72, resize: "vertical" }}
                placeholder="e.g. Small businesses waste hours manually reconciling invoices each month…"
                value={problem}
                onChange={(e) => setProblem(e.target.value)}
                aria-label="Problem or pain point"
              />
              {problem && (
                <button className="converter-clear-btn" onClick={() => setProblem("")} title="Clear">✕</button>
              )}
            </div>

            {/* Audience textarea */}
            <label htmlFor="audience-input" className="converter-label">
              Target audience <span style={{ color: "var(--ink-3)", fontWeight: 400 }}>(optional)</span>
            </label>
            <div className="converter-input-controls">
              <textarea
                id="audience-input"
                className="converter-input"
                style={{ minHeight: 56, resize: "vertical" }}
                placeholder="e.g. Freelance designers, solo founders, enterprise HR teams…"
                value={audience}
                onChange={(e) => setAudience(e.target.value)}
                aria-label="Target audience"
              />
              {audience && (
                <button className="converter-clear-btn" onClick={() => setAudience("")} title="Clear">✕</button>
              )}
            </div>

            <span className="converter-help-text" style={{ marginTop: 8 }}>
              Fill in any combination — the more detail, the more targeted the ideas
            </span>
          </div>

          {/* ── Generate button ── */}
          <div className="rng-controls" style={{ marginTop: 0 }}>
            <button
              className={`rng-generate-btn${loading ? " rolling" : ""}`}
              onClick={handleGenerate}
              disabled={loading}
              aria-label="Generate startup ideas"
            >
              {loading ? "⟳ Thinking with AI…" : count === 0 ? "✦ Generate Startup Ideas" : "✦ Generate Again"}
            </button>
          </div>

          {/* ── Error ── */}
          {errMsg && (
            <div className="converter-empty-state" role="alert" aria-live="assertive">
              <p>⚠ {errMsg}</p>
            </div>
          )}

          {/* ── Results ── */}
          {ideas.length > 0 && !errMsg && (
            <>
              <div
                className="converter-outputs"
                role="region"
                aria-live="polite"
                aria-label="Generated startup ideas"
                style={{ display: "flex", flexDirection: "column", gap: 1, background: "var(--line)", border: "1px solid var(--line)" }}
              >
                {ideas.map((idea) => {
                  const diff    = DIFFICULTY_META[idea.difficulty] ?? DIFFICULTY_META.medium;
                  const isOpen  = expanded === idea.name;
                  const isCopied = copied === idea.name;

                  return (
                    <div
                      key={idea.name}
                      style={{ background: "var(--bg)", transition: "background 0.2s" }}
                    >
                      {/* ── Card header (always visible) ── */}
                      <div
                        style={{
                          padding: "24px 28px 20px",
                          cursor: "pointer",
                          display: "flex",
                          flexDirection: "column",
                          gap: 8,
                        }}
                        onClick={() => toggleExpanded(idea.name)}
                        role="button"
                        tabIndex={0}
                        onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") toggleExpanded(idea.name); }}
                        aria-expanded={isOpen}
                      >
                        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap" }}>
                          <span
                            className="tool-cat"
                            style={{
                              borderColor: diff.color,
                              color: diff.color,
                              fontSize: 10,
                            }}
                          >
                            {diff.label}
                          </span>
                          <span style={{ fontSize: 16, color: "var(--ink-3)", transition: "transform 0.2s", transform: isOpen ? "rotate(45deg)" : "none" }}>+</span>
                        </div>

                        <code
                          className="output-code"
                          style={{ fontSize: "clamp(17px, 2.5vw, 26px)", lineHeight: 1.15, display: "block" }}
                        >
                          {idea.name}
                        </code>

                        <span style={{ fontSize: 13, color: "var(--accent)", fontFamily: "var(--mono)", fontStyle: "italic" }}>
                          &ldquo;{idea.tagline}&rdquo;
                        </span>
                      </div>

                      {/* ── Expanded details ── */}
                      {isOpen && (
                        <div style={{ padding: "0 28px 24px", display: "flex", flexDirection: "column", gap: 16 }}>
                          <div
                            style={{
                              display: "grid",
                              gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
                              gap: 1,
                              background: "var(--line)",
                              border: "1px solid var(--line)",
                            }}
                          >
                            {[
                              { label: "Problem",        value: idea.problem  },
                              { label: "Solution",       value: idea.solution },
                              { label: "Target Audience",value: idea.target   },
                              { label: "Revenue Model",  value: idea.revenue  },
                            ].map(({ label, value }) => (
                              <div key={label} style={{ background: "var(--surface)", padding: "14px 18px" }}>
                                <span className="output-label" style={{ marginBottom: 6, display: "block" }}>{label}</span>
                                <span style={{ fontSize: 13, color: "var(--ink)", lineHeight: 1.55 }}>{value}</span>
                              </div>
                            ))}
                          </div>

                          <button
                            className={`btn btn-ghost${isCopied ? " copied" : ""}`}
                            onClick={(e) => { e.stopPropagation(); copyIdea(idea); }}
                            style={{ alignSelf: "flex-start", fontSize: 12, padding: "8px 16px" }}
                            aria-label={`Copy idea: ${idea.name}`}
                          >
                            {isCopied ? "✓ Copied!" : "Copy idea"}
                          </button>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>

              <p style={{ marginTop: 12, fontSize: 12, color: "var(--ink-3)", fontFamily: "var(--mono)" }}>
                Powered by DeepSeek AI · batch #{count} · click any card to expand
              </p>
            </>
          )}

          {/* ── Empty state ── */}
          {ideas.length === 0 && !errMsg && (
            <div className="converter-empty-state">
              <p>Fill in your context above and click <strong>Generate Startup Ideas</strong></p>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}

// ── Page ──────────────────────────────────────────────────────────────────────
export default function StartupIdeaGeneratorPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareAppJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} />

      {/* HERO */}
      <section className="hero" aria-labelledby="hero-h1">
        <div className="hero-meta">
          <span className="dot dot-live" /> AI-Powered · DeepSeek · No Signup
        </div>
        <h1 id="hero-h1" className="hero-h1">
          Startup Idea Generator
          <br />
          <em>your next venture, now.</em>
        </h1>
        <p className="hero-sub">
          Describe a problem, an industry, or a target audience — get 4 specific, actionable
          startup ideas with problem, solution, revenue model, and difficulty rating.
          Powered by DeepSeek AI. Free, no signup.
        </p>
        <div className="hero-cta">
          <a href="#generator" className="btn btn-primary">Generate Ideas →</a>
          <a href="#how-it-works" className="btn btn-ghost">How it works</a>
        </div>
        <ul className="hero-stats" aria-label="Tool highlights">
          <li><strong>4</strong><span>ideas per batch</span></li>
          <li><strong>AI</strong><span>powered</span></li>
          <li><strong>14</strong><span>industries</span></li>
          <li><strong>Free</strong><span>forever</span></li>
        </ul>
      </section>

      {/* TOOL */}
      <StartupIdeaSection />

      {/* HOW IT WORKS */}
      <section id="how-it-works" className="why" aria-labelledby="why-h2">
        <span className="eyebrow">/ 01 — How It Works</span>
        <h2 id="why-h2" className="section-h2">Describe your context. Get ideas.</h2>
        <div className="why-grid">
          <article className="why-card">
            <span className="why-num">01</span>
            <h3>Set Your Context</h3>
            <p>Choose an industry, describe a problem you've noticed, or name your target audience. Any combination works — even just one field is enough.</p>
          </article>
          <article className="why-card">
            <span className="why-num">02</span>
            <h3>AI Generates 4 Ideas</h3>
            <p>DeepSeek AI produces 4 specific, actionable startup concepts — not generic buzzwords. Each idea includes a clear problem, solution, and revenue model.</p>
          </article>
          <article className="why-card">
            <span className="why-num">03</span>
            <h3>Expand to Read Details</h3>
            <p>Click any idea card to reveal the full breakdown: problem statement, solution, target audience, revenue model, and difficulty rating.</p>
          </article>
          <article className="why-card">
            <span className="why-num">04</span>
            <h3>Copy & Iterate</h3>
            <p>Copy any idea to your clipboard, refine your inputs, and generate again. Each batch uses high creativity settings so results are always different.</p>
          </article>
        </div>
      </section>

      {/* GUIDE */}
      <section className="why" aria-labelledby="guide-h2">
        <span className="eyebrow">/ 02 — Guide</span>
        <h2 id="guide-h2" className="section-h2">How to get better startup ideas.</h2>
        <div className="formats-container">
          <div className="format-group">
            <h3 className="format-group-title">Input tips</h3>
            <div className="format-items">
              <div className="format-item">
                <strong>Describe the pain, not the product</strong>
                <p>Don't say "I want a budgeting app". Say "freelancers forget to invoice clients and lose track of income." The AI will think of the product for you.</p>
                <code>Problem: "restaurants waste 30% of food weekly with no tracking"</code>
              </div>
              <div className="format-item">
                <strong>Be specific about your audience</strong>
                <p>The more specific your target, the better the idea. "SMEs" is vague. "Solo accountants managing 10-50 clients" gives the AI something to work with.</p>
                <code>Audience: "solo physical therapists running private practices"</code>
              </div>
              <div className="format-item">
                <strong>Use your founder background</strong>
                <p>Select your actual background. A "solo indie hacker" gets bootstrappable ideas. A "technical founder" gets ideas that leverage engineering skills.</p>
                <code>Background shapes: complexity, capital needs, go-to-market</code>
              </div>
            </div>
          </div>

          <div className="format-group">
            <h3 className="format-group-title">Understanding results</h3>
            <div className="format-items">
              <div className="format-item">
                <strong>Difficulty: Easy</strong>
                <p>Typically a service, no-code tool, or marketplace. Low capital required. Can often be validated and launched within a few weeks.</p>
                <code>Examples: newsletter, consulting service, Notion template marketplace</code>
              </div>
              <div className="format-item">
                <strong>Difficulty: Medium</strong>
                <p>Requires some development, industry knowledge, or a small team. 3-12 months to launch. Needs a few thousand dollars in capital.</p>
                <code>Examples: SaaS tool, mobile app, B2B platform</code>
              </div>
              <div className="format-item">
                <strong>Difficulty: Hard</strong>
                <p>Technically complex, capital-intensive, or regulated. Requires deep expertise, longer timelines, or significant funding to execute well.</p>
                <code>Examples: biotech, hardware, regulated fintech, AI infrastructure</code>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="faq" aria-labelledby="faq-h2">
        <span className="eyebrow">/ 03 — FAQ</span>
        <h2 id="faq-h2" className="section-h2">Questions people ask</h2>
        <div className="faq-list">
          {FAQ.map((f, i) => (
            <details key={i} className="faq-item">
              <summary>
                <span className="faq-q">{f.q}</span>
                <span className="faq-toggle" aria-hidden="true">+</span>
              </summary>
              <p>{f.a}</p>
            </details>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="cta">
        <h2>Ready to find your next startup idea?</h2>
        <a href="#generator" className="btn btn-primary btn-lg">Generate Ideas Now →</a>
      </section>
    </>
  );
}