import type { Metadata } from "next";
import Config from "@/lib/config";

import "@/style/home.css";

const breadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home",             item: Config.MAIN_DOMAIN_NO },
    { "@type": "ListItem", position: 2, name: "Terms of Service", item: `${Config.MAIN_DOMAIN_NO}/terms-of-service` },
  ],
};

const webPageJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: `Terms of Service — ${Config.SITE_NAME}`,
  url: `${Config.MAIN_DOMAIN_NO}/terms-of-service`,
  description: `Terms of Service for ${Config.SITE_NAME}. Free browser-based tools, no signup required. Read our usage terms, disclaimers, and intellectual property policy.`,
  publisher: {
    "@type": "Organization",
    name: Config.SITE_NAME,
    url: Config.MAIN_DOMAIN_NO,
  },
  dateModified: "2025-04-01",
};

export const metadata: Metadata = {
  title: `Terms of Service — ${Config.SITE_NAME}`,
  description: `Read the ${Config.SITE_NAME} Terms of Service. Learn how you may use our free browser-based tools, what we disclaim, and how to contact us with questions.`,
  alternates: { canonical: "/terms-of-service" },
  openGraph: {
    title: `Terms of Service — ${Config.SITE_NAME}`,
    description: `Usage terms for ${Config.SITE_NAME} free online tools. No signup, no data collection, 100% browser-based.`,
    url: `${Config.MAIN_DOMAIN_NO}/terms-of-service`,
    type: "website",
    siteName: Config.SITE_NAME,
  },
  robots: { index: true, follow: true },
};

const SECTIONS = [
  {
    num: "01",
    title: "Acceptance of terms",
    body: `By accessing or using any tool on ${Config.SITE_NAME} ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service. We may update these terms at any time — continued use after a change constitutes acceptance of the revised terms.`,
  },
  {
    num: "02",
    title: "Description of service",
    body: `${Config.SITE_NAME} provides a collection of free, browser-based utility tools including but not limited to: random number generator, password generator, QR code generator, UUID generator, color palette generator, hash generator, and others. All processing happens locally in your browser. No data you enter is transmitted to our servers.`,
  },
  {
    num: "03",
    title: "Permitted use",
    body: `You may use the Service for any lawful personal or commercial purpose. Output generated by our tools — passwords, random numbers, UUIDs, color palettes, QR codes, hashes, and similar — is yours to use freely without restriction or attribution. You may not use the Service to generate content that violates applicable laws or third-party rights.`,
  },
  {
    num: "04",
    title: "Prohibited use",
    body: `You agree not to: attempt to reverse-engineer, scrape, or systematically copy the Service; use automated tools to overload or disrupt the Service; attempt to gain unauthorised access to any part of the infrastructure; or use the Service for any purpose that is illegal or harmful to others.`,
  },
  {
    num: "05",
    title: "Intellectual property",
    body: `The ${Config.SITE_NAME} name, logo, design, and source code are the intellectual property of ${Config.SITE_NAME} and its creators. The tools and UI may not be reproduced, resold, or redistributed without explicit written permission. Output produced by the tools belongs entirely to you.`,
  },
  {
    num: "06",
    title: "Disclaimer of warranties",
    body: `The Service is provided "as is" and "as available" without warranties of any kind, express or implied. We do not warrant that the Service will be uninterrupted, error-free, or suitable for any particular purpose. You use the Service at your own risk. We are not responsible for any loss or damage arising from reliance on output generated by our tools.`,
  },
  {
    num: "07",
    title: "Limitation of liability",
    body: `To the fullest extent permitted by law, ${Config.SITE_NAME} and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of — or inability to use — the Service, even if advised of the possibility of such damages.`,
  },
  {
    num: "08",
    title: "Privacy & data",
    body: `${Config.SITE_NAME} does not collect, store, or transmit any data you enter into our tools. All computation runs locally in your browser. We may collect anonymous, aggregated analytics (page views, tool usage counts) to improve the Service. We do not use cookies for tracking or advertising.`,
  },
  {
    num: "09",
    title: "Third-party links",
    body: `The Service may contain links to third-party websites or resources. These are provided for convenience only. ${Config.SITE_NAME} has no control over, and assumes no responsibility for, the content or practices of any third-party sites.`,
  },
  {
    num: "10",
    title: "Changes to the service",
    body: `We reserve the right to modify, suspend, or discontinue any part of the Service at any time without notice. We will not be liable to you or any third party for any modification, suspension, or discontinuation of the Service.`,
  },
  {
    num: "11",
    title: "Governing law",
    body: `These Terms shall be governed by and construed in accordance with applicable law. Any disputes arising from these Terms or your use of the Service shall be resolved through good-faith negotiation where possible.`,
  },
  {
    num: "12",
    title: "Contact",
    body: `If you have any questions about these Terms of Service, please contact us at ${Config.GMAIL}. We read every message and reply within 1–2 business days.`,
  },
];

const FAQ = [
  { q: "Can I use the tools for commercial projects?",   a: "Yes. All output from our tools is yours to use in any personal or commercial project, free of charge and without attribution." },
  { q: "Do you collect my data?",                        a: "No. All processing runs locally in your browser. Nothing you type or generate is sent to our servers." },
  { q: "Can these terms change?",                        a: "Yes. We may update the Terms of Service at any time. Continued use of the Service after a change means you accept the updated terms." },
  { q: "Who do I contact with legal questions?",         a: `Reach us at ${Config.GMAIL}. We respond within 1–2 business days.` },
];

export default function TermsOfServicePage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(webPageJsonLd) }} />

      {/* HERO */}
      <section className="hero" aria-labelledby="hero-h1">
        <div className="hero-meta">
          <span className="dot dot-live" /> Last updated: April 2025 · Plain language · No legalese
        </div>
        <h1 id="hero-h1" className="hero-h1">
          Terms of Service
          <br />
          <em>written to be read.</em>
        </h1>
        <p className="hero-sub">
          Short version: use the tools freely, don't abuse the service, output is yours.
          Read the full terms below — we wrote them in plain English on purpose.
        </p>
        <div className="hero-cta">
          <a href="#terms" className="btn btn-primary">Read the terms →</a>
          <a href="#faq"   className="btn btn-ghost">Quick FAQ</a>
        </div>
        <ul className="hero-stats" aria-label="Terms highlights">
          <li><strong>Free</strong><span>to use</span></li>
          <li><strong>Output</strong><span>is yours</span></li>
          <li><strong>No</strong><span>data collected</span></li>
          <li><strong>Plain</strong><span>English</span></li>
        </ul>
      </section>

      {/* TERMS SECTIONS */}
      <section id="terms" className="tools" aria-labelledby="terms-h2">
        <div className="section-head">
          <div>
            <span className="eyebrow">/ 01 — Terms</span>
            <h2 id="terms-h2" className="section-h2">Full terms of service</h2>
            <p className="section-lede">
              These terms govern your use of {Config.SITE_NAME} and all tools available on the site.
              Effective date: April 1, 2025.
            </p>
          </div>
        </div>

        <ul className="tool-grid" role="list">
          {SECTIONS.map((s) => (
            <li key={s.num} className="tool-card">
              <div className="tool-top">
                <span className="tool-icon" aria-hidden="true">{s.num}</span>
              </div>
              <h3 className="tool-name">{s.title}</h3>
              <p className="tool-desc">{s.body}</p>
            </li>
          ))}
        </ul>
      </section>

      {/* WHY PLAIN TERMS */}
      <section className="why" aria-labelledby="why-h2">
        <span className="eyebrow">/ 02 — Our approach</span>
        <h2 id="why-h2" className="section-h2">Why we wrote it this way.</h2>
        <div className="why-grid">
          <article className="why-card">
            <span className="why-num">01</span>
            <h3>Plain language</h3>
            <p>Legal text should not require a lawyer to read. We wrote these terms to be understood by anyone in under five minutes.</p>
          </article>
          <article className="why-card">
            <span className="why-num">02</span>
            <h3>Output is yours</h3>
            <p>Everything you generate with our tools — passwords, numbers, UUIDs, palettes — belongs to you. No strings attached.</p>
          </article>
          <article className="why-card">
            <span className="why-num">03</span>
            <h3>No data collected</h3>
            <p>We genuinely don't want your data. All processing is local. There is nothing to store, sell, or leak.</p>
          </article>
          <article className="why-card">
            <span className="why-num">04</span>
            <h3>Questions welcome</h3>
            <p>If anything in these terms is unclear, email us. We will explain it or update the text to make it clearer.</p>
          </article>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="faq" aria-labelledby="faq-h2">
        <span className="eyebrow">/ 03 — FAQ</span>
        <h2 id="faq-h2" className="section-h2">Questions people ask</h2>
        <div className="faq-list">
          {FAQ.map((f, i) => (
            <details key={i} className="faq-item">
              <summary>
                <span className="faq-q">{f.q}</span>
                <span className="faq-toggle" aria-hidden="true">+</span>
              </summary>
              <p>{f.a}</p>
            </details>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="cta">
        <h2>Questions about these terms?</h2>
        <a href={`mailto:${Config.GMAIL}`} className="btn btn-primary btn-lg">
          Email us →
        </a>
      </section>
    </>
  );
}